config/routes.rb
Rails.application.routes.draw do

  root to: 'application#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :teams, only: [:show] do
    get '/matches', to: 'matches#index', as: 'matches'
  end

  resources :teams, only: [:index]
  resources :players
  resources :matches, only: [:index, :show, :new, :create]
  resources :leagues, only: [:index, :show]
  resources :notifications, only: [:index, :update]

  get '/teams/:id/add_players', to: 'player_teams#new', as: 'add_team_players'
  post '/teams/:id', to: 'player_teams#create'
  get '/teams/:id/edit_players', to: 'player_teams#edit', as: 'edit_team_players'
  patch '/teams/:id', to: 'player_teams#update'

  resources :users do
    resource :team
  end

end

app/models/league.rb
class League < ApplicationRecord
  has_many :teams

  def find_team_rank(team)
    teams = self.teams.order(wins: :desc)
    teams.find_index(team) + 1
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController


  def index
    @leagues = League.all
  end


  def show
    @league = League.find_by(id: current_user.league_id)
  end

end

app/views/leagues/_league_ranking_table.html.erb
<div class="container">
  <table class="table table-hover text-center">
    <thead>
      <tr>
        <th >Rank</th>
        <th>Name</th>
        <th>Manager</th>
        <th>Wins</th>
        <th>Losses</th>
        <th>Winning Percentage</th>
      </tr>
    </thead>
    <tbody>
      <% league.teams.order(wins: :desc).each_with_index do |team, index| %>
      <tr>

          <td class="text-left"><%= index + 1 %></td>
          <td class="text-left"> <%= link_to team.name, team_path(team) %> </td>
          <td class="text-left"> <%= team.user.name %> </td>
          <td class="text-left"> <%= team.wins %> </td>
          <td class="text-left"> <%= team.losses %> </td>
          <td class="text-left"> <%= sprintf("%.3f", team.winning_percentage) %> </td>

      </tr>
      <% end %>

    </tbody>
  </table>
</div>

app/views/leagues/index.html.erb
<div class="container text-center">
  <h1 class="red dodgeball">All League Standings</h1>
</div>

<%@leagues.each do |league| %>
  <h3 style="padding-left: 10px;"><%= league.name %></h3>
  <%= render partial: "league_ranking_table", locals: {league: league} %>
<% end %>

<br></br>

app/views/leagues/show.html.erb
<%= render partial: 'teams/team_tabs', locals: {team: current_user.team, user: current_user} %>

  <table class="table table-striped">
      <thead>
        <tr>
          <th>Rank</th>
          <th>Name</th>
          <th>Manager</th>
          <th>Wins</th>
          <th>Losses</th>
        </tr>
      </thead>
      <tbody>
        <% @league.teams.order(wins: :desc).each_with_index do |team, index| %>
        <tr>
            <td class="text-left"><%= index + 1 %></td>
            <td class="text-left"> <%= team.name %> </td>
            <td class="text-left"> <%= team.user.name %> </td>
            <td class="text-left"> <%= team.wins %> </td>
            <td class="text-left"> <%= team.losses %> </td>
        </tr>
      <% end %>

      </tbody>
    </table>