config/routes.rb
Rails.application.routes.draw do

  root to: 'application#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :teams, only: [:show] do
    get '/matches', to: 'matches#index', as: 'matches'
  end

  resources :teams, only: [:index]
  resources :players
  resources :matches, only: [:index, :show, :new, :create]
  resources :leagues, only: [:index, :show]
  resources :notifications, only: [:index, :update]

  get '/teams/:id/add_players', to: 'player_teams#new', as: 'add_team_players'
  post '/teams/:id', to: 'player_teams#create'
  get '/teams/:id/edit_players', to: 'player_teams#edit', as: 'edit_team_players'
  patch '/teams/:id', to: 'player_teams#update'

  resources :users do
    resource :team
  end

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :match

  def create_message
    if self.user.team == self.match.winning_team
      "You beat #{self.match.home_team.name}!"
    else
      "You lost to #{self.match.home_team.name} :("
    end
  end

  def display_date
    self.created_at.strftime('%A, %B %-d, %Y')
  end

  def self.unread
    self.where(unread: true)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = Notification.unread.where(user_id: current_user.id)
  end

  def update
    @notification = Notification.find_by(id: params[:id])
    @notification.update(unread: false)
    redirect_to notifications_path
  end

end

app/views/notifications/index.html.erb
<%= render partial: 'teams/team_tabs', locals: {team: current_user.team, user: current_user} %>

<div class="container text-center">
  <h2>Your Notifications</h2>

  <% if @notifications.empty? %>
    <p style="padding-bottom: 100px;">You don't have any notifications</p>
  <% else %>
    <% @notifications.each do |notification| %>
    <h4><%= notification.display_date %></h4>
    <%= notification.create_message %>
    <%= button_to "Mark as Read", notification_path(notification), :notification_id => notification.id, :method=>"patch"  %>
    <% end %>
  <% end %>
</div>