config/routes.rb
Rails.application.routes.draw do

  root to: 'application#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :teams, only: [:show] do
    get '/matches', to: 'matches#index', as: 'matches'
  end

  resources :teams, only: [:index]
  resources :players
  resources :matches, only: [:index, :show, :new, :create]
  resources :leagues, only: [:index, :show]
  resources :notifications, only: [:index, :update]

  get '/teams/:id/add_players', to: 'player_teams#new', as: 'add_team_players'
  post '/teams/:id', to: 'player_teams#create'
  get '/teams/:id/edit_players', to: 'player_teams#edit', as: 'edit_team_players'
  patch '/teams/:id', to: 'player_teams#update'

  resources :users do
    resource :team
  end

end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :home_team, class_name: 'Team'
  belongs_to :away_team, class_name: 'Team'
  has_many :notifications

  LOSS_MESSAGES = ["If you can’t dodge a wrench, you can’t dodge a ball. Start dodging wrenches.", "Ouchtown, population: You, bro!", "You're about as useful as a poopy flavored lollipop.", "You better learn the five d's of dodgeball: dodge duck dip dive and dodge", "Did you blindfold yourself?", "Damn you, Bernice!"]

  WIN_MESSAGES = ["If you can dodge a wrench, you can dodge a ball. Nice Work.", "Nobody makes you bleed your own blood!", "It’s a bold strategy, Cotton. But it paid off for them!", "If you can dodge traffic, you can dodge a ball!", "Patches is proud!", "Effin' A, Cotton, Effin' A!", "'L' for love! Good times!"]

  def assign_winner
    team_levels = [home_team.user.level, away_team.user.level]
    total_weight = team_levels.sum
    random_number = rand(1..total_weight)
    if random_number - team_levels[0] <= 0
      self.winning_team_id = home_team.id
    else
      self.winning_team_id = away_team.id
    end
    self.save
  end

  def update_standings
    if self.home_team_id == self.winning_team_id
      Team.find_by(id: home_team_id).add_win
      Team.find_by(id: away_team_id).add_loss
    else
      Team.find_by(id: home_team_id).add_loss
      Team.find_by(id: away_team_id).add_win
    end
  end

  def winning_team_rank_up
    wins = self.winning_team.wins
    case wins
    when 5
      winning_team.user.update(ranking_id: 2)
      "Congratulations, you are now an Underdog!"
    when 10
      winning_team.user.update(ranking_id: 3)
      "Congratulations, you are now an Average Joe!"
    when 50
      winning_team.user.update(ranking_id: 4)
      "Congratulations, you are now a Wrench Dodger!"
    when 100
      winning_team.user.update(ranking_id: 5)
      "Congratulations, you are now a DODGEBALL LEGEND!!!"
    end
  end

  def home_team
     Team.find_by(id: self.home_team_id)
  end

  def away_team
    Team.find_by(id: self.away_team_id)
  end

  def winning_team
    Team.find_by(id: self.winning_team_id)
  end

  def create_notification
    Notification.create(match_id: self.id, user_id: self.away_team.user_id)
  end

  def pick_match_message
    if self.home_team_id == self.winning_team_id
      WIN_MESSAGES.sample
    else
      LOSS_MESSAGES.sample
    end
  end

  def summary
    if self.home_team_id == self.winning_team_id
      "#{self.home_team.name} def. #{self.away_team.name}"
    else
      "#{self.away_team.name} def. #{self.home_team.name}"
    end
  end

  def display_date
    self.created_at.strftime('%A, %B %-d, %Y')
  end


end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  LOSS_MESSAGES = ["If you can’t dodge a wrench, you can’t dodge a ball. Start dodging wrenches.", "Ouchtown, population: You, bro!", "You're about as useful as a poopy flavored lollipop.", "You better learn the five d's of dodgeball: dodge duck dip dive and dodge", "Did you blindfold yourself?", "Damn you, Bernice!"]

  WIN_MESSAGES = ["If you can dodge a wrench, you can dodge a ball. Nice Work.", "Nobody makes you bleed your own blood!", "It’s a bold strategy, Cotton. But it paid off for them!", "If you can dodge traffic, you can dodge a ball!", "Patches is proud!", "Effin' A, Cotton, Effin' A!", "'L' for love! Good times!"]

  def index
    @team = Team.find_by(id: params[:team_id])
    @matches = @team.matches
  end

  def show
    @match = Match.find_by(id: params[:id])
  end

  def new
    if params[:search]
      @users = User.search_users(params[:search]).select{|user| user != current_user}
    else
      @users = User.all.select{|user| user != current_user}
    end
  end

  def create
    @match = Match.create(home_team_id: current_user.team.id, away_team_id: params[:away_team_id])
    @match.assign_winner
    @match.update_standings
    @match.create_notification
    @match.winning_team_rank_up
    flash[:message] = @match.pick_match_message
    redirect_to @match
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private

  def set_match
    @match = Match.find(params[:id])
  end

end

app/views/matches/index.html.erb
<%= render partial: 'teams/team_tabs', locals: {team: @team, user: @team.user} %>

<div class="container text-center">
  <h1>Matches</h1>
  <div>
    <% @matches.each do |match| %>
      <p><%= link_to match.summary, match_path(match), class: "red" %></p>
    <% end %>
  </div>
</div>

app/views/matches/new.html.erb
<div class="fluid-container wood-bg">
  <div class="container text-center">
    <h1>Play a Match!</h1>
    <h3>Choose your opponent: </h3>
  </div>

  <div class="search-from">
  <%= form_tag(new_match_path, :method => "get", id: "search-form") do %>
    <div class="input-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search for an opponent", class: "form-control"%>
        <span class="input-group-btn">
          <%= button_tag class: "btn btn-default" do %>
            <span class='glyphicon glyphicon-search'></span>
          </div>
      <% end %>
        </span>
    </div>
  <% end %>

  <br></br>

  <div class="container">
    <table class="table table-hover text-center">
        <thead>
          <tr>
          <th class="text-center">Team</th>
          <th class="text-center">Owner</th>
          <th class="text-center">Challenge</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <%@users.each do |user| %>
            <td class="text-center"><%= user.team.name %></td>
            <td class="text-center"><%= user.name %></td>
            <td class="text-center"><%= button_to "Challenge #{user.name}!", action: 'create', method: 'post', params: { away_team_id: user.team.id }, class: "btn btn-primary"%></td>
        </div>
        </tr>

    <% end %>
    </table>
  </div>
</div>

app/views/matches/show.html.erb
<div class="container text-center" style="padding-bottom: 40px;">
  <% if current_user.team == @match.winning_team %>
    <div class="text-success">
        <h1>YOU WON!</h1>
        <h2> <%= flash[:message] %></h2>
    </div>
  <% else %>
    <div class="text-danger">
      <h1>You Lost!</h1>
      <h2> <%= flash[:message] %></h2>
    </div>
  <% end %>
  <h1><%= @match.home_team.name%> vs. <%= @match.away_team.name %></h1>
  <h3>Winner: <%= @match.winning_team.name %></h3>
  <br></br>
  <h3><u>Match Summary</u></h3>
  <%= "#{@match.home_team.name} advance to #{@match.home_team.wins} - #{@match.home_team.losses}, now ##{@match.home_team.league.find_team_rank(@match.home_team)} in the #{@match.home_team.league.name} league." %> <br>
  <%= "#{@match.away_team.name} drop back to #{@match.away_team.wins} - #{@match.away_team.losses}, now ##{@match.away_team.league.find_team_rank(@match.away_team)} in the #{@match.away_team.league.name} league." %>
</div>