config/routes.rb
Rails.application.routes.draw do

  root to: 'application#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :teams, only: [:show] do
    get '/matches', to: 'matches#index', as: 'matches'
  end

  resources :teams, only: [:index]
  resources :players
  resources :matches, only: [:index, :show, :new, :create]
  resources :leagues, only: [:index, :show]
  resources :notifications, only: [:index, :update]

  get '/teams/:id/add_players', to: 'player_teams#new', as: 'add_team_players'
  post '/teams/:id', to: 'player_teams#create'
  get '/teams/:id/edit_players', to: 'player_teams#edit', as: 'edit_team_players'
  patch '/teams/:id', to: 'player_teams#update'

  resources :users do
    resource :team
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's Play Dodgeball!</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Shrikhand" rel="stylesheet">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="fluid-container red-bg" style="height: 7em">
      <div class="row">
        <h1 class="white dodgeball align-bottom" style="padding: 25px">Dodgeball!</h1>
      </div>
    </div>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <% if current_user %>
            <p class="navbar-brand dodgeball"><%= link_to "Hi, #{current_user.name}", user_team_path(current_user, current_user.team), class: "red dodgeball"%></p>
          <% end %>
        </div>
        <ul class="nav navbar-nav">
          <% if !logged_in? %>
            <li><%= link_to "Sign Up", new_user_path %></li>
            <li><%= link_to "Log In", login_path%></li>
          <% else %>
            <li><%= link_to "Teams", teams_path %></li>
            <li><%= link_to "Play Dodgeball!", new_match_path %> </li>
            <li><%= link_to "All League Standings", leagues_path %> </li>
            <li><%= link_to "League Players", players_path  %></li>
            <li><%= link_to "Sign Out", logout_path, method: :delete %> </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>

  <footer class="red-bg" style="padding-top: 40px;">
      <div class="row white" style="padding-left: 20px; font-size: 10px">
        <a class="white" href="mailto:morgannegagne@flatironschool.com"> Contact Us</a> <br>
        2018, All Rights Reserved
      </div>
    </div>
  </footer>
</html>